version: '3'

services:
  mysql:
    container_name: kingyucom.local.db
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "kingyu"
      MYSQL_PASSWORD: "kingyu"
      MYSQL_DATABASE: "kingyu_com"
    ports:
      - "3309:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"